import { pendantSettingsHtml, pendantSettingsScript } from './pendantSettingsPage';

export function pendantPage(token: string): string {
    return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>USB joystick — Luban</title><style>
body{font:17px system-ui;max-width:850px;margin:32px auto;padding:0 20px;background:#151b24;color:#eaf2ff}
button,input,select{font:inherit;padding:8px;margin:5px}input[type=number]{width:110px}
body.z-mode{background:#510d1b}#mode-banner{padding:12px;border:2px solid #55ddff;font-weight:bold}body.z-mode #mode-banner{background:#ae1731;border-color:#ffbac7;color:white}button{cursor:pointer}pre{white-space:pre-wrap;background:#222e3e;padding:16px}#stop{background:#ba2637;color:white}
#action{color:#ffcf70;white-space:pre-wrap;border-left:4px solid #ffcf70;padding:12px;background:#302a1b}#action:empty{display:none}#exclusions{white-space:pre-wrap}#state{font-size:1.3em;font-weight:bold}
</style><h1>USB joystick</h1><p>Connect the Feather's <b>USB data</b> port. Keep this page visible while jogging.</p>
<select id="port" aria-label="USB data port"></select><button id="connect" disabled>Connect / reconnect</button>
<pre id="dro" aria-label="Machine and work coordinates">Waiting for position…</pre>
<p id="link" role="status">Waiting for USB feedback…</p><p id="jog-timing"></p>
<p id="mode-banner" role="status">Waiting for joystick mode…</p><p id="state" role="status">Connecting to Luban…</p>
<p>Review the permitted envelope in <b>machine millimetres</b>. X/Y start at ±5 mm around the current position. Z defaults to 280–329 mm. Machine fill adds 1 mm at each end of the known X/Y travel.</p>
<form id="envelope"><fieldset id="review"><legend>Review jog bounds</legend><div id="bounds"></div>
<label>Maximum jog duration (seconds) <input id="segment-seconds" type="number" min="0.5" max="1" step="0.1" required></label><p>Distance follows feed: at 3000 mm/min, 0.5 seconds is 25 mm. Changing the stick uses shorter segments; a steady stick ramps to this limit.</p>
<button type="button" id="fill-x">Fill machine X (±1 mm)</button><button type="button" id="fill-y">Fill machine Y (±1 mm)</button><button type="button" id="fill-xy">Fill both X/Y (±1 mm)</button>
<p id="effective">Known travel unavailable.</p>
<p>Jogging is restricted to the requested bounds within known travel. The obstacle regions below remain excluded below their required machine Z. Every jog segment is checked; approval does not permit entering an excluded region.</p><p id="exclusions">Loading obstacle exclusions…</p>
<label><input id="clear" type="checkbox" required>I am supervising, the toolhead is off, I have reviewed the bounds and obstacle exclusions, and the remaining space clears the fitted tool and any unlisted obstacles.</label>
<p>Joystick button: switch twist between feed and Z. Twist adjusts feed (60–3000 mm/min) while connected, even disarmed; it starts at 300 mm/min when the Feather boots and is otherwise kept, except that Z mode caps it at 1000 mm/min. Hold only Feather <b>D1</b> to jog. Tap <b>D0</b> to switch MACHINE / WORK display; tap <b>D2</b> to stop and disarm.</p>
<button>Arm reviewed envelope (10 minutes)</button></fieldset></form><p id="action" role="alert" aria-live="assertive" tabindex="-1"></p><button id="stop">Stop / disarm</button>
<p>Stop prevents further jog segments; one accepted segment may finish (up to the approved 0.5–1 second of commanded travel, plus controller/transport delay). DRO and raw joystick diagnostics continue while disarmed.</p>
<p>If Luban refuses jogs because the controller is in the wrong workspace, restore its work frame first. This sends G90/G54 without moving any axis.</p><button id="restore-frame">Restore work frame (no motion)</button>
<p>Home raises Z and homes all axes, including rotary B: attached stock will rotate. This button permits homing despite stale position data; alarms and toolhead checks still apply. Jog Stop does not cancel an accepted homing command.</p><button id="home">Home all axes (including rotary B)</button>
${pendantSettingsHtml}
<details><summary>USB and machine diagnostics</summary><pre id="status"></pre></details>
<script>
const token=${JSON.stringify(token)},status=document.getElementById('status');
document.getElementById('segment-seconds').value=0.5;document.getElementById('segment-seconds').oninput=()=>{document.getElementById('clear').checked=false;};
const action=document.getElementById('action'),state=document.getElementById('state');
let travel=null,lastServerError=null,portListKey=null,connecting=false,lastDro=null,refreshing=false,armedNow=false,keepaliveInFlight=false,lastStatusOkAt=0,armGeneration=0;
function feedback(message,reveal=false){action.textContent=message;if(reveal){action.focus({preventScroll:true});action.scrollIntoView({block:'nearest'});}}
async function post(action,body={}){const r=await fetch('/pendant/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Pendant-Token':token},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw Error(p.error);return p;}
function requested(){const b={};for(const a of ['x','y','z'])for(const end of ['Min','Max'])b[a+end]=Number(document.getElementById(a+end).value);return b;}
function preview(){const b=requested();document.getElementById('effective').textContent=travel?'Usable machine bounds: '+['x','y','z'].map(a=>a.toUpperCase()+' '+Math.max(b[a+'Min'],travel[a+'Min']).toFixed(3)+' to '+Math.min(b[a+'Max'],travel[a+'Max']).toFixed(3)+' mm').join('; '):'Known travel unavailable. Arming is blocked.';for(const id of ['fill-x','fill-y','fill-xy'])document.getElementById(id).disabled=!travel;}
for(const a of ['x','y','z']){const row=document.createElement('div');row.textContent=a.toUpperCase()+' min / max ';for(const end of ['Min','Max']){const e=document.createElement('input');e.type='number';e.step='any';e.required=true;e.id=a+end;e.setAttribute('aria-label',a.toUpperCase()+' '+end);e.oninput=()=>{document.getElementById('clear').checked=false;preview();};row.appendChild(e);}document.getElementById('bounds').appendChild(row);}
function fill(axes){if(!travel)return;for(const a of axes){document.getElementById(a+'Min').value=travel[a+'Min']-1;document.getElementById(a+'Max').value=travel[a+'Max']+1;}document.getElementById('clear').checked=false;preview();}
document.getElementById('fill-x').onclick=()=>fill(['x']);document.getElementById('fill-y').onclick=()=>fill(['y']);document.getElementById('fill-xy').onclick=()=>fill(['x','y']);
function renderExclusions(boxes){document.getElementById('exclusions').textContent=boxes.length?'Obstacle exclusions (machine mm, including 5 mm XY margin):\\n'+boxes.map(b=>b.name+': X '+b.machine.x0+' to '+b.machine.x1+', Y '+b.machine.y0+' to '+b.machine.y1+'; '+(b.requiredZ===null?'all Z excluded until tool clearance is known':'requires Z ≥ '+b.requiredZ.toFixed(3))).join('\\n'):'No stored obstacle exclusions.';}
function renderPorts(ports,connected){const select=document.getElementById('port'),key=JSON.stringify(ports);if(key!==portListKey){const previous=select.value;select.textContent='';for(const p of ports){const e=document.createElement('option');e.value=p.path;e.textContent=p.path+' '+(p.serialNumber||'');select.appendChild(e);}select.value=ports.some(p=>p.path===previous)?previous:ports.some(p=>p.path===connected)?connected:ports[0]?.path||'';portListKey=key;}document.getElementById('connect').disabled=connecting||!select.value;}
function renderDro(dro,moving=false){const valid=dro&&!moving&&!dro.warnings?.length&&['verified','heartbeat','cached-offset'].includes(dro.reliability);if(valid)lastDro=JSON.parse(JSON.stringify(dro));const shown=valid?dro:lastDro;document.getElementById('dro').textContent=(valid?'':'Held values — waiting for verified position\\n')+['machine','work'].map(frame=>frame.toUpperCase()+': '+['x','y','z'].map(a=>a.toUpperCase()+' '+(Number.isFinite(shown?.[frame]?.[a])?shown[frame][a].toFixed(3):'—')).join('   ')).join('\\n');}
async function refreshPage(initial=false){const generation=armGeneration;try{const r=await fetch('/pendant/status');if(!r.ok)throw Error('Pendant status unavailable');const s=await r.json();status.textContent=JSON.stringify(s,null,2);renderPorts(s.ports||[],s.port);renderDro(s.dro,s.busy&&!s.recovery);document.getElementById('link').textContent=s.input?.feedback_ok===false?'USB feedback pending or delayed — jogging blocked':s.input?.round_trip_ms!=null?'USB round trip: '+s.input.round_trip_ms+' ms; input age: '+s.inputAgeMs+' ms':'USB feedback acknowledgement unavailable';const j=s.lastJog;document.getElementById('jog-timing').textContent=(j?'Last jog: '+j.distanceMm.toFixed(2)+' mm, '+Math.round(j.durationMs)+' ms commanded / '+j.elapsedMs+' ms including controller and link.':'')+(s.limitedAxes?.length?' At approved '+s.limitedAxes.join('/')+' limit; pull back to move away.':'');if(s.input){const zMode=s.input.mode==='z';document.body.classList.toggle('z-mode',zMode);document.getElementById('mode-banner').textContent=zMode?'DANGER: TWIST CONTROLS Z — hold D1 only when ready to move':'FEED ADJUST: twist changes feed rate';}if(s.error&&s.error!==lastServerError)feedback(s.error,true);lastServerError=s.error;document.getElementById('review').disabled=s.armed;document.getElementById('home').disabled=s.busy;document.getElementById('restore-frame').disabled=s.busy;state.textContent=s.armed?(s.neutral?'ARMED — hold D1 to jog':'ARMED — centre axes and release D1'):'DISARMED'+(s.busy?' — '+(s.recovery||'last accepted segment settling'):'');if(s.error)state.textContent+=': '+s.error;travel=s.travelBounds;renderExclusions(s.obstacleExclusions||[]);renderSettings(s.settings);if(initial){const bounds=s.armed?s.bounds:s.defaultBounds;if(bounds)for(const [k,v]of Object.entries(bounds))document.getElementById(k).value=Number(v.toFixed(3));if(s.armed)document.getElementById('segment-seconds').value=s.maxSegmentMs/1000;}if(generation===armGeneration)armedNow=s.armed;preview();lastStatusOkAt=Date.now();}catch(e){armedNow=false;renderDro(null);state.textContent='Status unavailable — '+e.message;}}
async function refresh(initial=false){if(refreshing)return;refreshing=true;try{await refreshPage(initial);}finally{refreshing=false;}}
document.getElementById('connect').onclick=async()=>{if(connecting||!document.getElementById('port').value)return;connecting=true;document.getElementById('connect').disabled=true;try{await post('connect',{path:document.getElementById('port').value});feedback('USB connected. Centre axes, review bounds, then Arm.');await refresh();}catch(e){feedback(e.message,true);}finally{connecting=false;await refresh();}};
document.getElementById('envelope').addEventListener('invalid',()=>{feedback('Enter valid bounds, a 0.5–1 second jog limit, and tick the clearance confirmation before arming.',true);},true);
document.getElementById('envelope').onsubmit=async(e)=>{e.preventDefault();try{await post('arm',{bounds:requested(),clearanceConfirmed:document.getElementById('clear').checked,maxSegmentMs:Number(document.getElementById('segment-seconds').value)*1000});armGeneration++;armedNow=true;lastStatusOkAt=Date.now();feedback('Arm accepted. Centre all axes and release D1 before jogging.');await refresh();}catch(err){await refresh();feedback(err.message,true);}};
document.getElementById('stop').onclick=async()=>{try{await post('disarm');await refresh();feedback('Stop accepted. Disarmed; live DRO and joystick diagnostics continue.',true);}catch(e){feedback('Stop request failed: '+e.message,true);}};
document.getElementById('restore-frame').onclick=async()=>{try{await post('restore-frame');await refresh();feedback('Work frame restored without axis motion. Wait for fresh coordinates before re-arming.',true);}catch(e){feedback(e.message,true);}};
document.getElementById('home').onclick=async()=>{document.getElementById('home').disabled=true;feedback('Homing requested; jogging disarmed. Waiting for fresh, verified completion…',true);try{await post('home',{confirmHoming:true});await refresh();feedback('Homing completed and verified. Review bounds and re-arm.',true);}catch(e){feedback('Home failed: '+e.message,true);}finally{await refresh();}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)post('disarm').catch(e=>{feedback('Disarm request failed: '+e.message,true);});});
${pendantSettingsScript}
// The keepalive has its own timer so one slow status poll cannot starve the 900 ms server limit,
// but it still proves a working page: it stops once status has not rendered for 1.5 s.
function keepalive(){if(!armedNow||document.hidden||keepaliveInFlight||Date.now()-lastStatusOkAt>1500)return;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),800);keepaliveInFlight=true;fetch('/pendant/keepalive',{method:'POST',headers:{'Content-Type':'application/json','X-Pendant-Token':token},body:'{}',signal:abort.signal}).then(r=>{if(!r.ok)armedNow=false;}).catch(()=>{}).finally(()=>{clearTimeout(timer);keepaliveInFlight=false;});}
refresh(true);setInterval(()=>refresh(),500);setInterval(keepalive,200);
</script></html>`;
}
