import { pendantSettingsHtml, pendantSettingsScript } from './pendantSettingsPage';

export function pendantPage(token: string): string {
    return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>USB joystick — Luban</title><style>
body{font:17px system-ui;max-width:850px;margin:32px auto;padding:0 20px;background:#151b24;color:#eaf2ff}
button,input,select{font:inherit;padding:8px;margin:5px}input[type=number]{width:110px}
body.z-mode{background:#510d1b}#mode-banner{padding:12px;border:2px solid #55ddff;font-weight:bold}body.z-mode #mode-banner{background:#ae1731;border-color:#ffbac7;color:white}button{cursor:pointer}pre{white-space:pre-wrap;background:#222e3e;padding:16px}#stop{background:#ba2637;color:white}
#action{color:#ffcf70;white-space:pre-wrap;border-left:4px solid #ffcf70;padding:12px;background:#302a1b}#action:empty{display:none}#exclusions{white-space:pre-wrap}#state{font-size:1.3em;font-weight:bold}
#map svg{display:block;width:100%;max-width:680px;height:auto;border:1px solid #33445a;background:#0e131a}
#blocked{font-weight:bold;color:#ffcf70;border-left:4px solid #ffcf70;padding:8px 12px;background:#302a1b}#blocked.held{color:#ffd0d6;border-color:#ff6b7d;background:#4a1220}#blocked:empty{display:none}#pipeline-note{color:#ffcf70;border-left:4px solid #ffcf70;padding:8px 12px}#pipeline-note:empty{display:none}
#obstacle-warning{white-space:pre-wrap;font-weight:bold;color:#fff;background:#7a1020;border:2px solid #ff6b7d;padding:12px}#obstacle-warning:empty{display:none}
#obstacle-table-wrap{overflow-x:auto}#obstacle-table{border-collapse:collapse;margin:8px 0;font-size:15px}#obstacle-table th,#obstacle-table td{border:1px solid #33445a;padding:4px 8px;text-align:left;vertical-align:top}#obstacle-table tr.danger td{background:#5a1420}
</style><h1>USB joystick</h1><p>Connect the Feather's <b>USB data</b> port. Keep this page visible while jogging.</p>
<select id="port" aria-label="USB data port"></select><button id="connect" disabled>Connect / reconnect</button>
<pre id="dro" aria-label="Machine and work coordinates">Waiting for position…</pre>
<p id="link" role="status">Waiting for USB feedback…</p><p id="jog-timing"></p>
<p id="mode-banner" role="status">Waiting for joystick mode…</p><p id="state" role="status">Connecting to Luban…</p>
<h2>Bed plan</h2><p>Machine X/Y seen from above, Y up as on the bed. Dashed blue: known travel. Green: the envelope you are reviewing (or the armed one). Boxes: stored obstacles with their 5 mm margin; red means your envelope reaches into one below its required Z. White dot: toolhead; a hollow amber ring is a held (not yet verified) position.</p>
<div id="map" role="img" aria-label="Plan view of travel, envelope, obstacles and toolhead"></div>
<p id="blocked" role="status" aria-live="polite"></p>
<p id="pipeline-note" role="status"></p>
<div id="obstacle-table-wrap"><table id="obstacle-table" aria-label="Obstacle exclusions"></table></div>
<p>Review the permitted envelope in <b>machine millimetres</b>. X/Y start at ±5 mm around the current position. Z defaults to 280–329 mm. Machine fill adds 1 mm at each end of the known X/Y travel.</p>
<form id="envelope"><fieldset id="review"><legend>Review jog bounds</legend><div id="bounds"></div>
<label>Maximum jog duration (seconds) <input id="segment-seconds" type="number" min="0.5" max="1" step="0.1" required></label><p>Settled jogs and Z: distance follows feed: at 3000 mm/min, 0.5 seconds is 25 mm. Changing the stick uses shorter segments; a steady stick ramps to this limit. Continuous X/Y jogging (when enabled) sends 100 ms increments instead and does not use this limit.</p>
<button type="button" id="fill-x">Fill machine X (±1 mm)</button><button type="button" id="fill-y">Fill machine Y (±1 mm)</button><button type="button" id="fill-xy">Fill both X/Y (±1 mm)</button>
<p id="effective">Known travel unavailable.</p>
<p>Jogging is restricted to the requested bounds, which may reach 1 mm past known travel on any axis: the machine accepts attempted overtravel and the DRO corrects on the next position sync. The obstacle regions below remain excluded below their required machine Z. Every jog segment is checked; approval does not permit entering an excluded region. A segment that would enter one is not sent: the pendant stays armed and holds, showing the obstacle and its required Z, and motion that stays out of it continues.</p><p id="exclusions">Loading obstacle exclusions…</p>
<label><input id="clear" type="checkbox" required>I am supervising, the toolhead is off, I have reviewed the bounds and obstacle exclusions, and the remaining space clears the fitted tool and any unlisted obstacles.</label>
<p>Joystick button: switch twist between feed and Z. Twist adjusts feed (60–3000 mm/min) while connected, even disarmed; it starts at 300 mm/min when the Feather boots and is otherwise kept, except that Z mode caps it at 1000 mm/min. Hold only Feather <b>D1</b> to jog. Tap <b>D0</b> to switch MACHINE / WORK display; tap <b>D2</b> to stop and disarm.</p>
<p id="obstacle-warning" role="alert"></p><button>Arm reviewed envelope (10 minutes)</button></fieldset></form><p id="action" role="alert" aria-live="assertive" tabindex="-1"></p><button id="stop">Stop / disarm</button>
<p>Stop prevents further jog segments; one accepted segment may finish (up to the approved 0.5–1 second of commanded travel, plus controller/transport delay; in continuous X/Y jogging at most the 0.2 s already queued, plus about half a round trip). DRO and raw joystick diagnostics continue while disarmed.</p>
<p>If Luban refuses jogs because the controller is in the wrong workspace, restore its work frame first. This sends G90/G54 without moving any axis.</p><button id="restore-frame">Restore work frame (no motion)</button>
<p>Home raises Z and homes all axes, including rotary B: attached stock will rotate. This button permits homing despite stale position data; alarms and toolhead checks still apply. Jog Stop does not cancel an accepted homing command.</p><button id="home">Home all axes (including rotary B)</button>
${pendantSettingsHtml}
<details><summary>USB and machine diagnostics</summary><pre id="status"></pre></details>
<script>
const token=${JSON.stringify(token)},status=document.getElementById('status');
document.getElementById('segment-seconds').value=0.5;document.getElementById('segment-seconds').oninput=()=>{document.getElementById('clear').checked=false;};
const action=document.getElementById('action'),state=document.getElementById('state');
let travel=null,lastServerError=null,portListKey=null,connecting=false,lastDro=null,refreshing=false,armedNow=false,keepaliveInFlight=false,lastStatusOkAt=0,armGeneration=0,mapStatus=null,droValid=false;
const A350_PLAN={xMin:-19,xMax:339,yMin:0,yMax:342};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);}
function mm(n){return String(Number(Number(n).toFixed(3)));}
// Required heights round up so the page never understates them.
function zUp(n){return String(Number((Math.ceil(Number(n)*100-1e-6)/100).toFixed(2)));}
function envelopeBounds(){const b=mapStatus&&mapStatus.armed&&mapStatus.bounds?mapStatus.bounds:requested(),e={};for(const a of ['x','y','z']){let lo=Number(b[a+'Min']),hi=Number(b[a+'Max']);if(travel){lo=Math.max(lo,travel[a+'Min']);hi=Math.min(hi,travel[a+'Max']);}if(!Number.isFinite(lo)||!Number.isFinite(hi)||hi<=lo)return null;e[a+'Min']=lo;e[a+'Max']=hi;}return e;}
// Same rule as the runtime's per-segment check: the XY envelope reaches the box and its Z floor is below the box's required Z.
function obstacleDanger(box,env){const m=box.machine;return !!env&&(box.requiredZ===null||env.zMin<box.requiredZ-0.05)&&env.xMin<=m.x1&&env.xMax>=m.x0&&env.yMin<=m.y1&&env.yMax>=m.y0;}
function obstacleWarning(box,env){const m=box.machine,area='X'+mm(m.x0)+'–'+mm(m.x1)+', Y'+mm(m.y0)+'–'+mm(m.y1)+' (incl. 5 mm margin)';return 'Your envelope Z '+mm(env.zMin)+'–'+mm(env.zMax)+' overlaps '+box.name+': '+(box.requiredZ===null?'tool clearance is unknown, so '+area+' is excluded at every height; jogs into it will be held, not sent.':'inside '+area+' the toolhead cannot go below Z'+zUp(box.requiredZ)+'; Z-down or entry there below Z'+zUp(box.requiredZ)+' will be held, not sent.');}
function renderMap(){
  const el=document.getElementById('map'),s=mapStatus;if(!s){el.innerHTML='';return;}
  const t=travel||A350_PLAN,boxes=s.obstacleExclusions||[],env=envelopeBounds();
  let x0=Math.min(t.xMin,A350_PLAN.xMin),x1=Math.max(t.xMax,A350_PLAN.xMax),y0=Math.min(t.yMin,A350_PLAN.yMin),y1=Math.max(t.yMax,A350_PLAN.yMax);
  for(const b of boxes){x0=Math.min(x0,b.machine.x0);x1=Math.max(x1,b.machine.x1);y0=Math.min(y0,b.machine.y0);y1=Math.max(y1,b.machine.y1);}
  x0-=14;x1+=14;y0-=22;y1+=14;
  const X=v=>(v-x0).toFixed(1),Y=v=>(y1-v).toFixed(1);
  const rect=(r,attrs)=>'<rect x="'+X(r.x0)+'" y="'+Y(r.y1)+'" width="'+Math.max(0,r.x1-r.x0).toFixed(1)+'" height="'+Math.max(0,r.y1-r.y0).toFixed(1)+'" '+attrs+'/>';
  const text=(x,y,value,attrs)=>'<text x="'+X(x)+'" y="'+Y(y)+'" '+(attrs||'')+'>'+esc(value)+'</text>';
  let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+(x1-x0).toFixed(1)+' '+(y1-y0).toFixed(1)+'" font-family="system-ui,sans-serif" font-size="9" fill="#eaf2ff">';
  svg+=rect({x0:t.xMin,x1:t.xMax,y0:t.yMin,y1:t.yMax},'fill="none" stroke="#55ddff" stroke-width="1" stroke-dasharray="4 3"');
  svg+=text(t.xMin,t.yMin-10,'X'+mm(t.xMin)+', Y'+mm(t.yMin),'fill="#55ddff"')+text(t.xMax,t.yMax+4,'X'+mm(t.xMax)+', Y'+mm(t.yMax),'fill="#55ddff" text-anchor="end"');
  svg+=text((t.xMin+t.xMax)/2,t.yMin-10,'X →  (machine mm, '+(travel?'known travel':'A350 bed; travel unknown')+')','fill="#9fb3c8" text-anchor="middle"');
  if(env)svg+=rect({x0:env.xMin,x1:env.xMax,y0:env.yMin,y1:env.yMax},'fill="#3fbf7f" fill-opacity="0.16" stroke="#3fbf7f" stroke-width="1.5"')+text(env.xMin+2,env.yMax-10,(s.armed?'armed':'envelope')+' Z '+mm(env.zMin)+'–'+mm(env.zMax),'fill="#7fe0aa"');
  for(const b of boxes){const m=b.machine,d=obstacleDanger(b,env),cx=(m.x0+m.x1)/2,cy=(m.y0+m.y1)/2;
    svg+='<g class="obstacle'+(d?' danger':'')+'" data-name="'+esc(b.name)+'">'+rect(m,d?'fill="#d0213f" fill-opacity="0.5" stroke="#ff6b7d" stroke-width="2"':'fill="#c98a1a" fill-opacity="0.28" stroke="#ffcf70" stroke-width="1"');
    svg+=text(cx,cy+3,b.name.slice(0,28),'text-anchor="middle" font-weight="bold" fill="#ffffff"')+text(cx,cy-8,b.requiredZ===null?'no entry: tool unknown':'needs Z ≥ '+zUp(b.requiredZ),'text-anchor="middle" fill="#ffffff"')+'</g>';}
  const live=droValid&&s.dro&&s.dro.machine,held=!live&&lastDro&&lastDro.machine,p=live?s.dro.machine:held;
  if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))svg+=live?'<g id="toolhead-live"><circle cx="'+X(p.x)+'" cy="'+Y(p.y)+'" r="4.5" fill="#ffffff" stroke="#151b24" stroke-width="1.5"/>'+text(p.x+7,p.y+3,'toolhead Z '+mm(p.z),'fill="#ffffff"')+'</g>':'<g id="toolhead-held"><circle cx="'+X(p.x)+'" cy="'+Y(p.y)+'" r="6" fill="none" stroke="#ffcf70" stroke-width="1.5" stroke-dasharray="2 2"/>'+text(p.x+8,p.y+3,'held (stale) Z '+mm(p.z),'fill="#ffcf70"')+'</g>';
  else svg+=text((t.xMin+t.xMax)/2,(t.yMin+t.yMax)/2,'Toolhead position unavailable','text-anchor="middle" fill="#ffcf70"');
  el.innerHTML=svg+'</svg>';
  const landmarks=(s.settings&&s.settings.landmarks)||[],dangers=boxes.filter(b=>obstacleDanger(b,env));
  document.getElementById('obstacle-warning').textContent=dangers.map(b=>obstacleWarning(b,env)).join('\\n');
  document.getElementById('obstacle-table').innerHTML=boxes.length?'<tr><th>Obstacle</th><th>Excluded machine XY (incl. 5 mm margin)</th><th>Toolhead needs Z ≥</th><th>Stored height (basis)</th><th>Notes</th><th>Your envelope</th></tr>'+boxes.map(b=>{const l=landmarks.find(x=>x.name===b.name),m=b.machine,d=obstacleDanger(b,env);
    const stored=!l?'—':l.clearanceZ===null?'not an obstruction':mm(l.clearanceZ)+' ('+(l.clearanceBasis==='physical'?'physical top':l.clearanceBasis==='toolhead'?'minimum toolhead Z':'toolhead Z, legacy default')+')';
    return '<tr'+(d?' class="danger"':'')+'><td>'+esc(b.name)+'</td><td>X '+mm(m.x0)+' to '+mm(m.x1)+', Y '+mm(m.y0)+' to '+mm(m.y1)+'</td><td>'+(b.requiredZ===null?'all Z excluded (tool unknown)':b.requiredZ.toFixed(3))+'</td><td>'+esc(stored)+'</td><td>'+esc(l?String(l.notes||l.description||'').slice(0,160):'')+'</td><td>'+(d?'OVERLAPS below required Z':'clear')+'</td></tr>';}).join(''):'';
}
function feedback(message,reveal=false){action.textContent=message;if(reveal){action.focus({preventScroll:true});action.scrollIntoView({block:'nearest'});}}
async function post(action,body={}){const r=await fetch('/pendant/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Pendant-Token':token},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw Error(p.error);return p;}
function requested(){const b={};for(const a of ['x','y','z'])for(const end of ['Min','Max'])b[a+end]=Number(document.getElementById(a+end).value);return b;}
function preview(){renderMap();const b=requested();document.getElementById('effective').textContent=travel?'Usable machine bounds (travel ±1 mm; the DRO corrects after overtravel): '+['x','y','z'].map(a=>a.toUpperCase()+' '+Math.max(b[a+'Min'],travel[a+'Min']-1).toFixed(3)+' to '+Math.min(b[a+'Max'],travel[a+'Max']+1).toFixed(3)+' mm').join('; '):'Known travel unavailable. Arming is blocked.';for(const id of ['fill-x','fill-y','fill-xy'])document.getElementById(id).disabled=!travel;}
for(const a of ['x','y','z']){const row=document.createElement('div');row.textContent=a.toUpperCase()+' min / max ';for(const end of ['Min','Max']){const e=document.createElement('input');e.type='number';e.step='any';e.required=true;e.id=a+end;e.setAttribute('aria-label',a.toUpperCase()+' '+end);e.oninput=()=>{document.getElementById('clear').checked=false;preview();};row.appendChild(e);}document.getElementById('bounds').appendChild(row);}
function fill(axes){if(!travel)return;for(const a of axes){document.getElementById(a+'Min').value=travel[a+'Min']-1;document.getElementById(a+'Max').value=travel[a+'Max']+1;}document.getElementById('clear').checked=false;preview();}
document.getElementById('fill-x').onclick=()=>fill(['x']);document.getElementById('fill-y').onclick=()=>fill(['y']);document.getElementById('fill-xy').onclick=()=>fill(['x','y']);
function renderExclusions(boxes){document.getElementById('exclusions').textContent=boxes.length?'Obstacle exclusions (machine mm, including 5 mm XY margin):\\n'+boxes.map(b=>b.name+': X '+b.machine.x0+' to '+b.machine.x1+', Y '+b.machine.y0+' to '+b.machine.y1+'; '+(b.requiredZ===null?'all Z excluded until tool clearance is known':'requires Z ≥ '+b.requiredZ.toFixed(3))).join('\\n'):'No stored obstacle exclusions.';}
function renderPorts(ports,connected){const select=document.getElementById('port'),key=JSON.stringify(ports);if(key!==portListKey){const previous=select.value;select.textContent='';for(const p of ports){const e=document.createElement('option');e.value=p.path;e.textContent=p.path+' '+(p.serialNumber||'');select.appendChild(e);}select.value=ports.some(p=>p.path===previous)?previous:ports.some(p=>p.path===connected)?connected:ports[0]?.path||'';portListKey=key;}document.getElementById('connect').disabled=connecting||!select.value;}
function renderDro(dro,moving=false){const valid=dro&&!moving&&!dro.warnings?.length&&['verified','heartbeat','cached-offset'].includes(dro.reliability);droValid=!!valid;if(valid)lastDro=JSON.parse(JSON.stringify(dro));const shown=valid?dro:lastDro;document.getElementById('dro').textContent=(valid?'':'Held values — waiting for verified position\\n')+['machine','work'].map(frame=>frame.toUpperCase()+': '+['x','y','z'].map(a=>a.toUpperCase()+' '+(Number.isFinite(shown?.[frame]?.[a])?shown[frame][a].toFixed(3):'—')).join('   ')).join('\\n');}
async function refreshPage(initial=false){const generation=armGeneration;const statusAbort=new AbortController(),statusTimer=setTimeout(()=>statusAbort.abort(),2000);try{const r=await fetch('/pendant/status',{signal:statusAbort.signal}).finally(()=>clearTimeout(statusTimer));if(!r.ok)throw Error('Pendant status unavailable');const s=await r.json();mapStatus=s;status.textContent=JSON.stringify(s,null,2);renderPorts(s.ports||[],s.port);renderDro(s.dro,s.busy&&!s.recovery);document.getElementById('link').textContent=s.input?.feedback_ok===false?'USB feedback pending or delayed — jogging blocked':s.input?.round_trip_ms!=null?'USB round trip: '+s.input.round_trip_ms+' ms; input age: '+s.inputAgeMs+' ms':'USB feedback acknowledgement unavailable';const j=s.lastJog;document.getElementById('jog-timing').textContent=(j?'Last jog: '+j.distanceMm.toFixed(2)+' mm, '+Math.round(j.durationMs)+' ms commanded / '+j.elapsedMs+' ms including controller and link.':'')+(s.limitedAxes?.length?' At approved '+s.limitedAxes.join('/')+' limit; pull back to move away.':'');if(s.input){const zMode=s.input.mode==='z';document.body.classList.toggle('z-mode',zMode);document.getElementById('mode-banner').textContent=zMode?'DANGER: TWIST CONTROLS Z — hold D1 only when ready to move':'FEED ADJUST: twist changes feed rate';}if(s.error&&s.error!==lastServerError)feedback(s.error,true);lastServerError=s.error;document.getElementById('review').disabled=s.armed;document.getElementById('home').disabled=s.busy;document.getElementById('restore-frame').disabled=s.busy;state.textContent=s.armed?(s.neutral?'ARMED — hold D1 to jog':'ARMED — centre axes and release D1'):'DISARMED'+(s.busy?' — '+(s.recovery||'last accepted segment settling'):'');if(s.error)state.textContent+=': '+s.error;const blocked=document.getElementById('blocked');blocked.textContent=s.armed&&s.blocked?s.blocked.text+(s.blocked.inside?' — the toolhead is inside this exclusion. Only a straight Z-up exit is sent: switch twist to Z and twist up. Every other move is held.':s.blocked.held?' — nothing sent, still armed. Move away from it or stay above its required Z.':' — only the part of the stick motion that stays clear was sent; still armed.'):'';blocked.className=s.armed&&s.blocked&&s.blocked.held?'held':'';if(s.armed&&s.blocked)state.textContent+=' — '+s.blocked.text;document.getElementById('pipeline-note').textContent=s.pipeline?.notice||'';travel=s.travelBounds;renderExclusions(s.obstacleExclusions||[]);renderSettings(s.settings);if(initial){const bounds=s.armed?s.bounds:s.defaultBounds;if(bounds)for(const [k,v]of Object.entries(bounds))document.getElementById(k).value=Number(v.toFixed(3));if(s.armed)document.getElementById('segment-seconds').value=s.maxSegmentMs/1000;}if(generation===armGeneration)armedNow=s.armed;preview();lastStatusOkAt=Date.now();}catch(e){armedNow=false;renderDro(null);renderMap();state.textContent='Status unavailable — '+e.message;}}
async function refresh(initial=false){if(refreshing)return;refreshing=true;try{await refreshPage(initial);}finally{refreshing=false;}}
document.getElementById('connect').onclick=async()=>{if(connecting||!document.getElementById('port').value)return;connecting=true;document.getElementById('connect').disabled=true;try{await post('connect',{path:document.getElementById('port').value});feedback('USB connected. Centre axes, review bounds, then Arm.');await refresh();}catch(e){feedback(e.message,true);}finally{connecting=false;await refresh();}};
document.getElementById('envelope').addEventListener('invalid',()=>{feedback('Enter valid bounds, a 0.5–1 second jog limit, and tick the clearance confirmation before arming.',true);},true);
document.getElementById('envelope').onsubmit=async(e)=>{e.preventDefault();try{await post('arm',{bounds:requested(),clearanceConfirmed:document.getElementById('clear').checked,maxSegmentMs:Number(document.getElementById('segment-seconds').value)*1000});armGeneration++;armedNow=true;lastStatusOkAt=Date.now();feedback('Arm accepted. Centre all axes and release D1 before jogging.');await refresh();}catch(err){await refresh();feedback(err.message,true);}};
document.getElementById('stop').onclick=async()=>{try{await post('disarm');await refresh();feedback('Stop accepted. Disarmed; live DRO and joystick diagnostics continue.',true);}catch(e){feedback('Stop request failed: '+e.message,true);}};
document.getElementById('restore-frame').onclick=async()=>{try{await post('restore-frame');await refresh();feedback('Work frame restored without axis motion. Wait for fresh coordinates before re-arming.',true);}catch(e){feedback(e.message,true);}};
document.getElementById('home').onclick=async()=>{document.getElementById('home').disabled=true;feedback('Homing requested; jogging disarmed. Waiting for fresh, verified completion…',true);try{await post('home',{confirmHoming:true});await refresh();feedback('Homing completed and verified. Review bounds and re-arm.',true);}catch(e){feedback('Home failed: '+e.message,true);}finally{await refresh();}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)post('disarm').catch(e=>{feedback('Disarm request failed: '+e.message,true);});});
${pendantSettingsScript}
// The keepalive has its own timer so one slow status poll cannot starve the 900 ms server limit,
// but it still proves a working page: it stops once status has not rendered for 1.5 s.
// Keep the laptop screen on while armed: a dimmed screen lets the browser throttle the keepalive timer.
let wakeLock=null;function holdScreenAwake(){if(armedNow&&!wakeLock&&typeof navigator!=='undefined'&&navigator.wakeLock&&!document.hidden){navigator.wakeLock.request('screen').then(l=>{wakeLock=l;l.addEventListener('release',()=>{wakeLock=null;});}).catch(()=>{});}else if(!armedNow&&wakeLock){wakeLock.release().catch(()=>{});wakeLock=null;}}
function keepalive(){holdScreenAwake();if(!armedNow||document.hidden||keepaliveInFlight||Date.now()-lastStatusOkAt>1500)return;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),800);keepaliveInFlight=true;fetch('/pendant/keepalive',{method:'POST',headers:{'Content-Type':'application/json','X-Pendant-Token':token},body:'{}',signal:abort.signal}).then(r=>{if(!r.ok)armedNow=false;return r.text();}).catch(()=>{}).finally(()=>{clearTimeout(timer);keepaliveInFlight=false;});}
refresh(true);setInterval(()=>refresh(),500);setInterval(keepalive,200);
</script></html>`;
}
